# This is a basic workflow to help you get started with Actions

name: Build and Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # OS ubuntu on container
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python Environment
        uses: actions/setuo-python@v3.0.0
        
      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Test
        run: |
          flake8 app.py
          pytlint app.py
          
  deploy:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
        application_name: flask-app-ci-cd
        environment_name: Flaskappcicd-env
        
        version_label: 12348
        region: "eu-west-3"
        deployment_package: deploy.zip
          
      
        
      
      
      

