# This is a basic workflow to help you get started with Actions

name: CICD from github to aws EC2
  # AWS_REGION_NAME           : "eu-west-3"
on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  workflow_dispatch:
jobs:
    build:
       runs-on: ubuntu-latest
       steps:
         - name: check your repository
           uses: actions/checkout@v2
            
         - name: Setup Python Environment
           uses: actions/setup-python@v3.0.0
           
         - name: Install dependancies
           run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

         - name: Run Test
           run: |
            flake8 app.py
            pylint app.py
         
         - name: Print nice message TEST OK
           run : echo "TEST part finished successfully"